### ISSUE TITLE
 can not download the KITTI test dataset from the provided Google Drive website

### ISSUE THREAD

**Issue by Feegooddddd** [ZhiChen902/SC2-PCR-plusplus#1]
Thank you for excellent works ! But I can not download the KITTI test dataset from the provided Google Drive website, could you please privide the BaiduNetdisk Download that I will appreciate.

**Comment by ZhiChen902** [comment]
Thank you for your attention. The Baidu Netdisk for downloading the KITTI test dataset is now available. You can find it in readme file.
![image](https://github.com/ZhiChen902/SC2-PCR-plusplus/assets/54473539/2faad6cb-67f6-41a3-853b-9f8447372f4a)

**Comment by Feegooddddd** [comment]
Thank you very much!
