### ISSUE TITLE
About FPFH Matching on KITTI

### ISSUE THREAD

**Issue by qiaozhijian** [ZhiChen902/SC2-PCR-plusplus#2]
Thanks for your nice work!

On the KITTI benchmark, how do you preprocess point cloud and extract FPFH descriptor?

I implement it by myself but get a low success ratio. The code is [here](https://github.com/qiaozhijian/SC2-PCR-plusplus/blob/main/misc/registration.py#L11). Config file is [here](https://github.com/qiaozhijian/SC2-PCR-plusplus/blob/main/configs/dataset.yaml).

**Comment by BorSch90** [comment]
For FPFH features, you're missing the critical 
```
src_features = src_features / (np.linalg.norm(src_features, axis=1, keepdims=True) + 1e-6)
tgt_features = tgt_features / (np.linalg.norm(tgt_features, axis=1, keepdims=True) + 1e-6)
```
at line 24 in your code file

**Comment by qiaozhijian** [comment]
Thanks. I will try.
